export interface Athlete {
    id: string,
    fullName: string,
    age: number,
    bench: number,
    squat: number,
    deadlift: number,
    total?: number,
    isActive: JSX.Element | boolean,
    federation: string,
    last_comp?: string,
    next_comp?: string,
    gold_medals?: number,
    silver_medals?: number,
    bronze_medals?: number,
}